### ISSUE TITLE
[feat] unit tests

### ISSUE THREAD

**Issue by douglas-pires** [heyhoio/heyho#12]
All we know how tests are important to keep any application scalable and healthy. Currently, for the sake of implementing the maximum of features possible, we didn't write tests. We know that this is not scalable, though. Let's fix the problem.

**Describe the solution you'd like**
Unit tests for all functionalities.

**Tasks**
- [x] Box shadow generator
- [x] Color Picker
- [x] Credit Card Generator
- [x] CSS filters
- [x] Regex Replace Viewer
